
--SELECIONANDO REGISTROS

SELECT [ID] , [NOME], [TELEFONE] FROM TBCONTATO

--SELECIONANDO UM REGISTRO

SELECT [ID] , [NOME], [TELEFONE] FROM TBCONTATO WHERE [ID] = 4;

--INSERINDO REGISTROS
INSERT INTO [TBCONTATO] 
		( 
			[NOME], 
			[TELEFONE]
		)
		VALUES
		(
			'Marcus',
			'(+55) 9999-9999'
		);

--EXCLUINDO UM REGISTRO
DELETE FROM [TBCONTATO] WHERE [ID] = 3;

--ATUALIZANDO UM REGISTRO
UPDATE [TBContato]
		SET
			[Nome] = 'RECEBA',
			[Telefone] = '9999999999'

		WHERE 
			[ID] = 5;

